name: Validate Commit

on:
  push:
    branches:
    - main
    - 'fix/*'
    - 'feature/*'
    paths:
    - '**'
    - '!docs/**'

  pull_request:
    branches:
    - main
    paths:
    - '**'
    - '!docs/**'

jobs:
  format:
    runs-on: ubuntu-latest
    name: DotNet Format
    steps:
      - uses: actions/checkout@v3
      - run: dotnet tool install -g dotnet-format
      - run: dotnet format ./ --folder --check --exclude **/AddFormats/
